title: Left Join Labs
email:
description: Custom CiviCRM development
url: https://leftjoinlabs.com
baseurl: ""
markdown: kramdown
sass:
  sass_dir: css
  style:    expanded
collections:
- sections
- services
- people
- model
- partnerships
ignore:
- bin
