title: Left Join Labs
email: info@leftjoinlabs.com
description: Custom CiviCRM development
url: https://leftjoinlabs.com
baseurl: ""
markdown: kramdown
sass:
  sass_dir: css
  style:    expanded
collections:
- services
- people




